type: yml

discord:
  name: "CamCheckBot"
  max_wait_seconds: 30
  token: "MTE5MTAzMDQ1NDY3ODIxMjcyOA.GYJG8Y.bRC6e5euR1aZ1nk8gKDsJg-eT-5d_451Qa2k8w"

database:
  redis:
    port: "6379"
    host: "localhost"
    password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    db: 0
  mongodb:
    port: 27017
    host: localhost
    db_name: db
    username: michael
    password: secret
