type: yml

discord:
  name: CamCheckBot
  max_wait_seconds: 30
  token: YOUR_DISCORD_BOT_TOKEN

database:
  redis:
    port: 6379
    host: redis
    password: ""
    db_name: 0
  mongodb:
    port: 27017
    host: mongo
    db_name: db
    username: mongouser
    password: mongopassword
